# Generated by Django 5.1.15 on 2026-10-02 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=80)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('artista', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('CONCIERTO', 'Concierto'), ('FESTIVAL', 'Festival'), ('TEATRO', 'Teatro'), ('DEPORTE', 'Deporte'), ('OTRO', 'Otro')], default='CONCIERTO', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to=settings.AUTH_USER_MODEL)),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='catalogo.recinto')),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='catalogo.evento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evento', 'nombre'), name='sector_unico_por_evento')],
            },
        ),
    ]
