# Generated by Django 5.1.15 on 2026-10-07 20:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='asientos_por_fila',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='sector',
            name='filas',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(26)]),
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=2)),
                ('numero', models.PositiveSmallIntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='catalogo.sector')),
            ],
            options={
                'ordering': ['fila', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('sector', 'fila', 'numero'), name='asiento_unico_por_sector')],
            },
        ),
    ]
