# Generated by Django 5.1.15 on 2026-10-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='evento',
        ),
    ]
