# Generated by Django 5.1.15 on 2026-10-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_sector_asientos_por_fila_sector_filas_asiento'),
        ('ventas', '0002_remove_carro_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='asientos',
            field=models.ManyToManyField(blank=True, related_name='detalles_orden', to='catalogo.asiento'),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='asientos',
            field=models.ManyToManyField(blank=True, related_name='items_carro', to='catalogo.asiento'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogo.asiento'),
        ),
    ]
